### PR TITLE
Chief Ernest Shonekan, General Ibrahim Babangida

### PR DESCRIPTION
**Pull request by Anushh23**
Chief Ernest Shonekan, General Ibrahim Babangida

### CODE REVIEW

**Comment by unclebay143** [comment]
Seems we have a merge conflict to fix, let me know if you need help with it

image

**Comment by Anushh23** [comment]
I know it is closed but can you help with why this happened?

**Comment by unclebay143** [comment]
Sure 

You need to update your branch with the current main branch which is mine.

The reason the error shows up is that, some contributors like you have made changes before you completed your own pull request.


Which means the repository has some changes that you do not have.

Now to solve this.


You need to update your branch.


How.

Use the fetch button to update with mine, 

Them on your gitbash 

Run git pull origin main (that's main of your own branch)


Now you will notice the changes to the project 


Make your changes and make a new pull request and it should be fine

**Comment by Anushh23** [comment]
Ohh, thanks a lot!
Will take care from now:)

**Pull request closed without merging**
